"""
config_loader.py
Loads b2b_config.json so the same .exe can be shipped to different clients
with different default die sizes, materials, and report branding - without
touching any code.
"""

import json
import os
import sys

CONFIG_FILENAME = "b2b_config.json"

DEFAULTS = {
    "client_name": "Unlicensed",
    "default_die_width_mm": 4.68,
    "default_die_height_mm": 5.97,
    "default_material": "Silicon",
    "report_footer_text": "Generated by Thermal Digital Twin",
    "report_logo_path": "assets/default_logo.png",
}


def _get_config_path():
    if getattr(sys, "frozen", False):
        base_dir = os.path.dirname(sys.executable)
    else:
        base_dir = os.path.dirname(os.path.abspath(__file__))
    return os.path.join(base_dir, CONFIG_FILENAME)


def load_config():
    path = _get_config_path()
    if not os.path.exists(path):
        return DEFAULTS.copy()

    try:
        with open(path, "r") as f:
            data = json.load(f)
        merged = DEFAULTS.copy()
        merged.update(data)
        return merged
    except (json.JSONDecodeError, OSError):
        return DEFAULTS.copy()
